model_provider = "sccpu7schenfgpluslocal"
disable_response_storage = true
preferred_auth_method = "apikey"
personality = "pragmatic"

[model_providers.sccpu7schenfgpluslocal]
name = "sccpu7schenfgpluslocal"
base_url = "http://localhost:58317/v1"
wire_api = "responses"
requires_openai_auth = true
